---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-fs-api
  name: pttg-fs-api
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
    targetPort: https
  - port: 8080
  selector:
    name: pttg-fs-api
