---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pttg-fs-service
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-fs-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-fs-service
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      initContainers:
        - name: get-ca-certs
          image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.2
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-fs-service.${KUBE_NAMESPACE}.svc.cluster.local
            - --onetime=true
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: create-truststore
          image: quay.io/ukhomeofficedigital/pttg-docker-openjdk8:latest
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          volumeMounts:
            - name: store
              mountPath: /store
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -alias servercert -file /etc/ssl/certs/ca-bundle.crt -keystore /store/truststore.jks -noprompt -storepass changeit"]
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/pttg-cfssl-sidekick:build-6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-fs-service.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: store
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
