---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-fs-service
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-fs-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-fs-service
        version: {{.VERSION}}

      annotations:
        pod.beta.kubernetes.io/init-containers: '
[
   {
      "name": "vaultjks",
      "image": "quay.io/ukhomeofficedigital/vaultjks:v0.1.0",
      "imagePullPolicy": "Always",
      "env": [
         {
            "name": "VAULT_ADDR",
            "value": "https://vault.vault.svc.cluster.local:8200"
         },
         {
            "name": "VAULT_TOKEN",
            "valueFrom": {
               "secretKeyRef": {
                  "name": "store-token",
                  "key": "token"
               }
            }
         },
         {
            "name": "VAULT_PKI_PATH",
            "value": "services/pt-i-{{.ENVIRONMENT}}/pki"
         },
         {
            "name": "VAULT_ROLE_NAME",
            "value": "default"
         },
         {
            "name": "SLEEP_FOREVER",
            "value": "false"
         },
         {
            "name": "IP_SAN",
            "valueFrom": {
               "fieldRef": {
                  "apiVersion": "v1",
                  "fieldPath": "status.podIP"
               }
            }
         }
      ],
      "volumeMounts": [
         {
            "mountPath": "/data",
            "name": "javapki"
         }
      ]
   }
]
        '
    spec:
      imagePullSecrets:
      - name: registrykey
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.2
        securityContext:
          runAsNonRoot: true
        args:
          - --certs=/etc/nginx/secrets
          - --domain=pttg-fs-service.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
          # The platform CA Bundle hold the root ca used to verify the certificate chain
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
#      - name: vault-sidekick
#        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
#        imagePullPolicy: Always
#        resources:
#         limits:
#          memory: "100Mi"
#          cpu: 100m
#         requests:
#          memory: "50Mi"
#          cpu: 100m
#        args:
#          - -output=/etc/nginx/secrets
#          - -tls-skip-verify=true
#          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=pttg-fs-service.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/pttg-fs-service,fmt=bundle
#        env:
#          - name: VAULT_ADDR
#            value: "https://vault.vault.svc.cluster.local:8200"
#          - name: NAMESPACE
#            valueFrom:
#              fieldRef:
#                fieldPath: metadata.namespace
#          - name: VAULT_TOKEN
#            valueFrom:
#              secretKeyRef:
#                name: store-token
#                key: token
#        volumeMounts:
#          - mountPath: /etc/nginx/secrets
#            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/pttg-nginx-proxy:v3.1.3a
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/pttg-fs-service-bundle.pem
          - name: SERVER_KEY
            value: /etc/nginx/secrets/pttg-fs-service-key.pem
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      - name: pttg-fs-service
        image: quay.io/ukhomeofficedigital/pttg-fs-service:{{.VERSION}}
        imagePullPolicy: Always
        env:
          - name: JAVA_OPTS
            value: '-Xms150m -Xmx250m -Djavax.net.ssl.trustStore=/data/truststore.jks'
          - name: SERVER_PORT
            value: '8080'
          - name: BARCLAYS_SERVICE_URL
            value: "https://pttg-fs-barclays.pt-i-{{.ENVIRONMENT}}.svc.cluster.local"
          - name: JDK_TRUST_FILE
            value: '/data/truststore.jks'
          - name: AUDITING_MONGODB_HOST
            value: 'pttg-mongodb.pt-i-{{.ENVIRONMENT}}.svc.cluster.local'
          - name: AUDITING_DEPLOYMENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: AUDITING_DEPLOYMENT_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 1600m
            memory: 612Mi
          requests:
            cpu: 100m
            memory: 484Mi
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /data
            name: javapki
            readOnly: true
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
      - name: javapki
        emptyDir:
          medium: "Memory"
