---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pttg-fs-service
  labels:
    version: {{.VERSION}}
spec:
  replicas: 2
  selector:
    matchLabels:
      name: pttg-fs-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-fs-service
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      initContainers:
        - name: get-ca-certs
          image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.2
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-fs-service.${KUBE_NAMESPACE}.svc.cluster.local
            - --onetime=true
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: create-truststore
          image: quay.io/ukhomeofficedigital/pttg-docker-openjdk8:latest
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          volumeMounts:
            - name: store
              mountPath: /store
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          command: ["/bin/sh"]
          args: ["-c", "keytool -import -alias servercert -file /etc/ssl/certs/ca-bundle.crt -keystore /store/truststore.jks -noprompt -storepass changeit"]
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/pttg-cfssl-sidekick:build-6
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --domain=pttg-fs-service.${KUBE_NAMESPACE}.svc.cluster.local
            - --expiry=8760h
            - --command=/usr/local/scripts/trigger_nginx_reload.sh
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: pttg-fs-service
          image: quay.io/ukhomeofficedigital/pttg-fs-service:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          env:
            - name: JAVA_OPTS
              value: '-Xms150m -Xmx250m -Djavax.net.ssl.trustStore=/store/truststore.jks'
            - name: SERVER_PORT
              value: '8080'
            - name: BARCLAYS_SERVICE_URL
              value: "https://pttg-fs-barclays.pttg-fs-{{.ENVIRONMENT}}.svc.cluster.local"
            - name: JDK_TRUST_FILE
              value: '/store/truststore.jks'
            - name: AUDITING_MONGODB_HOST
              value: 'pttg-mongodb.pttg-fs-{{.ENVIRONMENT}}.svc.cluster.local'
            - name: AUDITING_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUDITING_DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 1600m
              memory: 612Mi
            requests:
              cpu: 100m
              memory: 484Mi
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: X-probe
                  value: kubelet
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: store
              mountPath: /store
              readOnly: true
      volumes:
        - name: store
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
